#!/usr/bin/env bash

#  Author: Bhagat Shubham <bhagat.shubham7@gmail.com>

# notificator is a tool that runs the command you supplied and then sends you
# a push notification when the command has finished running

# Before using it you need to configure the values of EVENT_NAME, ACCESS_KEY and
# INCLUDE_COMMAND_IN_MESSAGE.
# You may do so either by setting the appropriate environment variables
# or editing the default values below.
# Alternatively, run the finito-config.sh script which will do this for you.

# The webhook event name you chose for your applet
#EVENT_NAME_read=${EVENT_NAME}
# Your IFTTT webhook key from: https://ifttt.com/maker_webhooks/settings
#ACCESS_KEY_read=${ACCESS_KEY}
# Toggle whether you want to include the command you ran in the push notification message
#INCLUDE_COMMAND_IN_MESSAGE=1

# Run the command
COMMAND="$*"
$COMMAND

# Formulate the exit code text
COMMAND_EXIT_CODE=$?
if [ $COMMAND_EXIT_CODE -eq 0 ]
then
    COMMAND_RESULT="SUCCESS ✔️"
else
    COMMAND_RESULT="FAILURE ❌"
fi


JSON_PAYLOAD='{"value1":"'${COMMAND}'","value2":"'${COMMAND_RESULT}'"}'
API_URL=https://maker.ifttt.com/trigger/${EVENT_NAME}/with/key/${ACCESS_KEY}

CURL_OUTPUT=$(curl -X POST -H "Content-Type: application/json" -d "${JSON_PAYLOAD}" ${API_URL} 2>/dev/null)

# Uncomment to see the output of the curl command in case of issues
# echo ${CURL_OUTPUT}

exit $COMMAND_EXIT_CODE
